# Generated by Django 2.2 on 2019-08-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190804_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='mobile',
            field=models.CharField(max_length=50, verbose_name='电话号码'),
        ),
    ]
