# Generated by Django 2.2 on 2019-08-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190804_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='邮箱', max_length=100, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, help_text='电话号码', max_length=11, null=True, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, help_text='用户名', max_length=30, null=True, unique=True, verbose_name='用户名'),
        ),
    ]
